routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth','prefix' => 'admin', 'as' => 'admin.'], function(){ 
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);
        
        Route::group(['middleware' => ['permission:view-banner|banner-modification|add-new-banner']], function () {
            Route::resource('banners','BannerController');
        });

        Route::group(['middleware' => ['permission:view-partner|partner-modification|add-new-partner']], function () {
            Route::resource('partners','PartnerController');
        });

        Route::group(['middleware' => ['permission:view-event|event-modification|add-new-event']], function () {
            Route::resource('events','EventController');
        });

        Route::group(['middleware' => ['permission:view-member|member-modification|add-new-member']], function () {
            Route::resource('members','MemberController');
        });
        Route::group(['middleware' => ['permission:view-gallery|gallery-modification|add-new-gallery']], function () {
            Route::resource('galleries','GalleryController');
        });
        Route::group(['middleware' => ['permission:view-principle|principle-modification|add-new-principle']], function () {
            Route::resource('principles','PrincipleController');
        });
        Route::group(['middleware' => ['permission:view-setting|setting-modification']], function () {
            Route::resource('settings','SettingController');
        });
        Route::group(['middleware' => ['permission:view-language|language-modification']], function () {
            Route::resource('languages','LanguageController');
        });
        Route::group(['middleware' => ['permission:download-register-user']], function () {
            Route::get('member-registers/pdf/{id}',['uses' => 'MemberRegisterController@downloadPdf', 'as' => 'member-registers.download']);
        });   
        Route::group(['middleware' => ['permission:view-register-user|delete-register-user|download-register-user']], function () {
            Route::resource('member-registers','MemberRegisterController');
        });
        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
        Route::post('/save-multi-temp-image', ['as' => 'dropzoneSaveMultiTempImage', 'uses' => 'ImageController@dropzoneSaveMultiTempImage']);
        Route::post('/save-summernote-image',['as' => 'summernoteSaveImage', 'uses' => 'ImageController@summernoteSaveImage']);
        Route::get('/get-image-list-by-object',['as' => 'getImageList', 'uses' => 'ImageController@getImageList']);
        Route::post('/delete-image-by-object',['as' => 'deleteDropzoneImage', 'uses' => 'ImageController@deleteDropzoneImage']);
    });  
});

Route::group(['namespace' => 'Client','as' =>'client.'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'LanguageController@index', 'as' => 'set-locale']);
    Route::get('/',['uses' => 'FrontendController@index','as' => 'homepage']);
    Route::get('/galleries',['uses' => 'FrontendController@gallery', 'as' => 'gallery']);
    Route::get('/events',['uses' => 'FrontendController@event', 'as' => 'event']);
    Route::get('/events/{id}',['uses' => 'FrontendController@eventDetail', 'as' => 'event-detail']);
    Route::get('/about-us',['uses' => 'FrontendController@aboutUs', 'as' => 'about']);
    Route::get('/register',['uses' => 'FrontendController@registerForm', 'as' => 'register']);
    Route::post('/register',['uses' => 'FrontendController@register', 'as' => 'register']);
});

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Gallery;
use App\Model\Province;
use DB;

class GalleryController extends Controller
{
    public function __construct(){
        $this->middleware('permission:view-gallery',   ['only' => ['index']]);
        $this->middleware('permission:add-new-gallery',   ['only' => ['create']]);
        $this->middleware('permission:gallery-modification',   ['only' => ['update','destroy']]);
    }

    public function index()
    {
        $galleries = Gallery::with('province')->orderBy('id','DESC')->paginate(10);

        return view('admin.gallery.index',compact('galleries'));
    }

    public function create()
    {
        $provinces = Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        $provinces = ['0' => 'Choose Location'] + $provinces;
        return view('admin.gallery.add-update',compact('provinces'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'galleryDropzoneImage' => 'required',
            'location' => 'required|max:100',
            'galleryMulitDropzoneImage' => 'required'
        ]);
        $this->saveToDB($request->all());
        return redirect()->route('admin.galleries.index')->withSuccess('You have just added a gallery successfully!');
    }

    public function edit($id)
    {
        $provinces = Province::orderBy('name','ASC')->pluck('name','id')->toArray();
        $provinces = ['0' => 'Choose Location'] + $provinces;
        $gallery = Gallery::findOrFail($id);
        return view('admin.gallery.add-update',compact('gallery','provinces'));
    }

    public function update(Request $request, $id)
    {  
        $this->validate($request,[
            'location' => 'required|max:100',
        ]);
        $this->saveToDB($request->all(),$id);
        return redirect()->route('admin.galleries.index')->withSuccess('You have just updated a gallery successfully!');
    }

    public function destroy($id)
    {
       $result = false;
       $gallery = Gallery::find($id);
       if($gallery){
           DB::beginTransaction();
           try{
               if($gallery->delete()){
                   $result = true;
               }
               DB::commit();
           }catch(Exception $exception){
               DB::rollback();
               $result = false;
           }
       }
       return response()->json(['success' => $result]);
    }

    public function saveToDB($data, $id=null){
        DB::beginTransaction();
        try{
            $gallery = isset($id) ? Gallery::find($id) : new Gallery;
            if(!$gallery) return redirect()->back()->withError('There is no record found!');

            $gallery->fill($data);
            if($gallery->save()){
                saveModelSingleImage($gallery,$data['galleryDropzoneImage'],'images');
                saveModelMultiImage($gallery,$data['galleryMulitDropzoneImage'],'album'); 
                if(isset($id) && $data['galleryMulitDropzoneDelete']){ 
                    deleteModelMultiImage($gallery,$data['galleryMulitDropzoneDelete'],'album');
                }
            }

            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError('There was an error during operation!');
        }
        return $gallery;
    }
}

resources/views/admin/gallery/add-update.blade.php
@extends('admin.layouts.master')

@section('page-css')
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/icheck/icheck.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/forms/icheck/custom.css">
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ isset($gallery) ? 'Update' : 'Add' }} Gallery</h4>
            </div>

            @if(isset($gallery))
            {{ Form::model($gallery,['route' => ['admin.galleries.update',$gallery->id], 'method' => 'PUT']) }}
            @else
            {{ Form::open(['route' => 'admin.galleries.store', 'method' => 'POST']) }}
            @endif
            @csrf
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <fieldset class="form-group">
                                <label for="basicInput"> Province / City </label>
                                {!! Form::select('province_id',$provinces,null,['class' => 'form-control custom-select block']) !!}
                                @component('common.error_helper_text',['key' => "name"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="basicInput">Location <span class="text-danger">*</span></label>
                                {!! Form::text('location',null,['class' => 'form-control', 'placeholder' => 'Enter location']) !!}
                                @component('common.error_helper_text',['key' => "location"])@endcomponent
                            </fieldset>
                        </div>
                        <div class="col-md-4">
                            <fieldset class="form-group">
                                <label>Album Thumbnail (Aspec Ratio 3:2) <span class="text-danger">*</span></label>
                                @component('common.single_dropzone',['id' => "galleryDropzone",'object' => isset($gallery) ? $gallery : null, 'width' => 260, 'height' => 160])@endcomponent
                            </fieldset>
                        </div>
                        <div class="col-md-12">
                            <fieldset class="form-group">
                                <label>Album Images (Aspec Ratio 3:2) <span class="text-danger">*</span></label>
                                @component('common.multi_dropzone',['id' => "galleryMulitDropzone",'object' => isset($gallery) ? $gallery : null, 'width' => 180, 'height' => 120])@endcomponent
                            </fieldset>
                        </div>
                    </div>
                </div>

                @if(isset($gallery))
                    @can('gallery-modification')
                    <div class="card-footer">
                        <a href="{{route('admin.galleries.index')}}" class="btn grey btn-outline-secondary">Discard</a>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                    @endcan
                @else
                    @can('add-new-gallery')
                    <div class="card-footer">
                        <a href="{{route('admin.galleries.index')}}" class="btn grey btn-outline-secondary">Discard</a>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                    @endcan
                @endif
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/gallery/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Gallery Albums</h4>
                @can('add-new-gallery')
                <div class="heading-elements">
                    <a href="{{route('admin.galleries.create')}}" class="btn btn-sm btn-icon btn-success">
                        <i class="ft-plus white"></i> Add New
                    </a>
                </div>
                @endcan
            </div>
            <div class="card-content">
                <div class="card-body">
                    @include('admin.includes.success-msg')
                    @include('admin.includes.error-msg')
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-light">
                                <th>#</th>
                                <th>Thumbnail</th>
                                <th>Location</th>
                                <th>Province/City</th>
                                <th style="min-width:100px;">Action</th>
                            </thead>
                            <tbody>
                                <tr>
                                    @if(isset($galleries) && $galleries->count() > 0)
                                        @foreach($galleries as $key => $row)
                                        @php $image = $row->getMedia('images')->first(); @endphp
                                        <tr>
                                            <td>{{($galleries->perPage() * ($galleries->currentPage() - 1)) + $key + 1}}</td>
                                            <td>
                                                <img width="120px" height="80px" style="object-fit: cover" class="" src="{{$image ? $image->getUrl() : ''}}" alt="">
                                            </td>
                                            <td>{!! $row->location !!}</td>
                                            <td>{!! $row->province ? $row->province->name : '' !!}</td>
                                            <td class="group-btn-action">
                                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                                    <a href="{{ route('admin.galleries.edit',$row->id) }}" class="btn btn-outline-warning"><i class="ft-edit-3"></i> Edit</a>
                                                    @can('gallery-modification')
                                                    <button type="button" class="btn btn-outline-danger delete" data-route="{{route('admin.galleries.destroy',$row->id)}}"><i class="ft-trash-2"></i> Delete</button>
                                                    @endcan
                                                </div>
                                            </td>
                                        </tr>
                                        @endforeach
                                    @else
                                        <tr><td colspan="5">No Data</td></tr>
                                    @endif
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @if(isset($galleries) && $galleries->count() > 0)
            <div class="card-footer">
                <div class="mb-2">
                    {!! $galleries->appends(Request::except('page'))->render() !!}
                </div>
                <div>
                    Showing {{$galleries->firstItem()}} to {{$galleries->lastItem()}}
                    of  {{$galleries->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection