routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth','prefix' => 'admin', 'as' => 'admin.'], function(){ 
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);
        
        Route::group(['middleware' => ['permission:view-banner|banner-modification|add-new-banner']], function () {
            Route::resource('banners','BannerController');
        });

        Route::group(['middleware' => ['permission:view-partner|partner-modification|add-new-partner']], function () {
            Route::resource('partners','PartnerController');
        });

        Route::group(['middleware' => ['permission:view-event|event-modification|add-new-event']], function () {
            Route::resource('events','EventController');
        });

        Route::group(['middleware' => ['permission:view-member|member-modification|add-new-member']], function () {
            Route::resource('members','MemberController');
        });
        Route::group(['middleware' => ['permission:view-gallery|gallery-modification|add-new-gallery']], function () {
            Route::resource('galleries','GalleryController');
        });
        Route::group(['middleware' => ['permission:view-principle|principle-modification|add-new-principle']], function () {
            Route::resource('principles','PrincipleController');
        });
        Route::group(['middleware' => ['permission:view-setting|setting-modification']], function () {
            Route::resource('settings','SettingController');
        });
        Route::group(['middleware' => ['permission:view-language|language-modification']], function () {
            Route::resource('languages','LanguageController');
        });
        Route::group(['middleware' => ['permission:download-register-user']], function () {
            Route::get('member-registers/pdf/{id}',['uses' => 'MemberRegisterController@downloadPdf', 'as' => 'member-registers.download']);
        });   
        Route::group(['middleware' => ['permission:view-register-user|delete-register-user|download-register-user']], function () {
            Route::resource('member-registers','MemberRegisterController');
        });
        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
        Route::post('/save-multi-temp-image', ['as' => 'dropzoneSaveMultiTempImage', 'uses' => 'ImageController@dropzoneSaveMultiTempImage']);
        Route::post('/save-summernote-image',['as' => 'summernoteSaveImage', 'uses' => 'ImageController@summernoteSaveImage']);
        Route::get('/get-image-list-by-object',['as' => 'getImageList', 'uses' => 'ImageController@getImageList']);
        Route::post('/delete-image-by-object',['as' => 'deleteDropzoneImage', 'uses' => 'ImageController@deleteDropzoneImage']);
    });  
});

Route::group(['namespace' => 'Client','as' =>'client.'],function(){
    Route::get('/language/set-locale/{locale}',['uses' => 'LanguageController@index', 'as' => 'set-locale']);
    Route::get('/',['uses' => 'FrontendController@index','as' => 'homepage']);
    Route::get('/galleries',['uses' => 'FrontendController@gallery', 'as' => 'gallery']);
    Route::get('/events',['uses' => 'FrontendController@event', 'as' => 'event']);
    Route::get('/events/{id}',['uses' => 'FrontendController@eventDetail', 'as' => 'event-detail']);
    Route::get('/about-us',['uses' => 'FrontendController@aboutUs', 'as' => 'about']);
    Route::get('/register',['uses' => 'FrontendController@registerForm', 'as' => 'register']);
    Route::post('/register',['uses' => 'FrontendController@register', 'as' => 'register']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\Models\Media;

class User extends Authenticatable implements HasMedia
{
    use Notifiable, HasRoles, HasMediaTrait;

    protected $fillable = [ 
        'name', 'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct(){
        $this->middleware('permission:view-user',   ['only' => ['index']]);
        $this->middleware('permission:add-new-user',   ['only' => ['create']]);
        $this->middleware('permission:user-modification',   ['only' => ['update','destroy']]);
    }

    public function index()
    {
        $users = User::paginate(15);
        return view('admin.user.index',compact('users'));
    }

    public function create()
     {
         $roles = [0 => 'Choose a role'] + Role::all()->pluck('name','id')->toArray();
         return view('admin.user.add-update',compact('roles'));
     }
 
     public function store(Request $request)
     {
         $this->validate($request,[
             'name' => 'required|unique:users,name',
             'email' => 'required|unique:users,email',
             'password' => 'required|confirmed|min:6',
             'password_confirmation' => 'required|min:6'
         ]);
         
         $this->saveToDB($request->all());
         return redirect()->route('admin.users.index')->withSuccess('You have just added a user successfully!');
     }

     public function edit($id)
     {
         $roles = [0 => 'Choose a role'] + Role::all()->pluck('name','id')->toArray();
         $user = User::findOrFail($id);
         return view('admin.user.add-update',compact('roles','user'));
     }
 
     public function update(Request $request, $id)
     {
         $this->validate($request,[
             'name' => 'required|unique:users,name,'.$id,
             'email' => 'required|unique:users,email,'.$id
         ]);
         
         if($request->password){
             $this->validate($request,[
                 'password' => 'required|confirmed|min:6',
                 'password_confirmation' => 'required',
             ]);
         }
 
         $this->saveToDB($request->all(),$id);
         return redirect()->route('admin.users.index')->withSuccess('You have just updated a user successfully!');
     }

     public function destroy($id)
     {
        $result = false;
        $user = User::find($id);
        if($user){
            DB::beginTransaction();
            try{
                if($user->delete()){
                    $result = true;
                }
                DB::commit();
            }catch(Exception $exception){
                DB::rollback();
                $result = false;
            }
        }
        return response()->json(['success' => $result]);
     }

    public function deleteImage(){
        $result = false;
        $user_id = request()->get('user_id');
        DB::beginTransaction();
        try{
            $user = User::findOrFail($user_id);
            if($user){
                $user->clearMediaCollection('images');
                $result = true;
            }
            DB::commit();
        }catch(Exception $exception){
            DB::rollback();
            $result = false;
        }
        
        return response()->json(['success' => $result]);
    }

     public function saveToDB($data, $id=null){
         DB::beginTransaction();
         try{
             $user = isset($id) ? User::find($id) : new User;
             if(!$user) return redirect()->back()->withError('There is no record found!');
    
             if($data['password']){
                 $data['password'] = Hash::make($data['password']);
             }else{
                 unset($data['password']);
             }
             $user->fill($data);
             if($user->save()){
                $role = Role::find($data['role_id']);
                if($role) $user->syncRoles([$role->name]);
                saveModelSingleImage($user,$data['profileDropzoneImage'],'images');
             }

             DB::commit();
         }catch(Exception $ex){
             DB::rollback();
             return redirect()->back()->withError('There was an error during operation!');
         }
         return $user;
     }
}

resources/views/admin/user/add-update.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">            
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ isset($user) ? 'Update' : 'Add' }} Administrator users</h4>
            </div>

            @if(isset($user))
            {{ Form::model($user,['route' => ['admin.users.update',$user->id], 'method' => 'PUT']) }}
            @else
            {{ Form::open(['route' => 'admin.users.store', 'method' => 'POST']) }}
            @endif
            @csrf
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 order-lg-1 mb-md-2">
                            <fieldset class="form-group">
                                <label>Profile Image (Aspec Ratio 1:1)</label>
                                @component('common.single_dropzone',['id' => "profileDropzone",'object' => isset($user) ? $user : null, 'width' => 150, 'height' => 150])@endcomponent
                            </fieldset>
                        </div>
                        <div class="col-md-6 order-lg-21 mb-md-2">
                            <fieldset class="form-group">
                                <label for="">Admininstrator Name</label>
                                {!! Form::text('name',null,['class' => 'form-control', 'placeholder' => 'Enter your name']) !!}
                                @component('common.error_helper_text',['key' => "name"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Email</label>
                                {!! Form::email('email',null,['class' => 'form-control', 'placeholder' => 'Enter email']) !!}
                                @component('common.error_helper_text',['key' => "email"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Password</label>
                                {!! Form::password('password',['class' => 'form-control', 'placeholder' => 'Please enter more than 6 characters']) !!}
                                @component('common.error_helper_text',['key' => "password"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Password Confirmation</label>
                                {!! Form::password('password_confirmation',['class' => 'form-control', 'placeholder' => 'Please enter more than 6 characters']) !!}
                                @component('common.error_helper_text',['key' => "password_confirmation"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Role Authority</label>
                                {!! Form::select("role_id",$roles, isset($user,$user->roles[0]) ? $user->roles[0]->id : null,['class' => 'custom-select block']) !!}
                                @component('common.error_helper_text',['key' => "role_id"])@endcomponent
                            </fieldset>
                        </div>
                    </div>
                </div>
                
                <div class="card-footer">
                    <a href="{{route('admin.users.index')}}" class="btn grey btn-outline-secondary">Discard</a>
                    <button type="submit" class="btn btn-outline-primary">Save changes</button>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit-profile.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">            
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ isset($user) ? 'Update' : 'Add' }} Administrator users</h4>
            </div>

            {{ Form::model($user,['route' => ['admin.users.profile.update',$user->id], 'method' => 'PUT']) }}
            @csrf
            <div class="card-content">
                <div class="card-body">
                    @include('admin.includes.success-msg')
                    <div class="row">
                        <div class="col-lg-6 order-lg-1 mb-md-2">
                            <fieldset class="form-group">
                                <label>Profile Image (Aspec Ratio 1:1)</label>
                                @component('common.single_dropzone',
                                    ['id' => "profileDropzone",'object' => isset($user) ? $user : null, 'width' => 200, 'height' => 200])
                                @endcomponent
                            </fieldset>
                        </div>
                        <div class="col-lg-6 order-lg-21 mb-md-2">
                            <fieldset class="form-group">
                                <label for="">Admininstrator Name</label>
                                {!! Form::text('name',null,['class' => 'form-control', 'placeholder' => 'Enter your name']) !!}
                                @component('common.error_helper_text',['key' => "name"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Email</label>
                                {!! Form::email('email',null,['class' => 'form-control', 'placeholder' => 'Enter email']) !!}
                                @component('common.error_helper_text',['key' => "email"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Password</label>
                                {!! Form::password('password',['class' => 'form-control', 'placeholder' => 'Please enter more than 6 characters']) !!}
                                @component('common.error_helper_text',['key' => "password"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Password Confirmation</label>
                                {!! Form::password('password_confirmation',['class' => 'form-control', 'placeholder' => 'Please enter more than 6 characters']) !!}
                                @component('common.error_helper_text',['key' => "password_confirmation"])@endcomponent
                            </fieldset>
                            <fieldset class="form-group">
                                <label for="">Role Authority</label>
                                {!! Form::text("role",isset($user,$user->roles[0]) ? $user->roles[0]->name : null,['class' => 'form-control', 'disabled']) !!}
                                @component('common.error_helper_text',['key' => "role_id"])@endcomponent
                            </fieldset>
                        </div>
                    </div>
                </div>
                
                <div class="card-footer">
                    <button type="submit" class="btn btn-outline-primary">Save changes</button>
                </div>
            </div>

            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Administrators</h4>
                <div class="heading-elements">
                    @can('add-new-user')
                    <a href="{{route('admin.users.create')}}" class="btn btn-sm btn-icon btn-success">
                        <i class="ft-plus white"></i> Add New
                    </a>
                    @endcan
                </div>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class="bg-primary">
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    @if(isset($users) && $users->count() > 0)
                                        @foreach($users as $key => $row)
                                        @php $image = $row->getMedia('images')->first() @endphp
                                        <tr style="vertical-align:middle">
                                            <td>{{($users->perPage() * ($users->currentPage() - 1)) + $key + 1}}</td>
                                            @if($image)
                                                <td> <img class="rounded-circle" width="35px;" src="{{$image->geturl()}}"> {{ $row->name }}</td>
                                            @else
                                                <td>{{ $row->name }}</td>
                                            @endif
                                            <td>{{ $row->email }}</td>
                                            <td>{{ $row->roles && isset($row->roles[0]) ? $row->roles[0]->name : '-' }}</td>
                                            <td class="group-btn-action">
                                                @canany(['user-modification'])
                                                    <div class="btn-group btn-group-sm" aria-label="Basic example">
                                                        <a href="{{ route('admin.users.edit',$row->id) }}" class="btn btn-outline-warning"><i class="ft-edit-3"></i> Edit</a>
                                                        <button type="button" class="btn btn-outline-danger delete" data-route="{{route('admin.users.destroy',$row->id)}}"><i class="ft-trash-2"></i> Delete</button>
                                                    </div>
                                                @endcanany
                                            </td>
                                        </tr>
                                        @endforeach
                                    @else
                                        <tr><td colspan="3">No Data</td></tr>
                                    @endif
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @if(isset($users) && $users->count() > 0)
            <div class="card-footer">
                <div class="mb-2">
                    {!! $users->appends(Request::except('page'))->render() !!}
                </div>
                <div>
                    Showing {{$users->firstItem()}} to {{$users->lastItem()}}
                    of  {{$users->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection

@section('page-script')

<script>
</script>
@endsection